### PR TITLE
Bot token??? Where do I add

### PR DESCRIPTION
**Pull request by RXNationGMG**
Beuh

### CODE REVIEW

**Comment by a-newusername** [comment]
**botsettings.json**

^^^^^^^^^^^^^

**Comment by a-newusername** [comment]
make a post in issue not pull request next time

**Comment by a-newusername** [comment]
ALSO you leaked your bot token

download it and extract it then change it not make a pull request to try to **change the token for everyone**

now remember to generate a new bot token

**Comment by Wyliemaster** [comment]
The token goes in the "token" field in botsettings.json as ggamerzz said. Also yeah, be sure to reset your token before trying, your token is supposed to be private

**Comment by BruhMe-r** [comment]
Here the old & stupid pull request xD

**Pull request closed without merging**
